### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by cjsb** [Unity-Technologies/Unity-Experimental-DXR#2]
Hi,

I tried to create a new project with the DXR template but I got this error. What shoud I do?

![image](https://user-images.githubusercontent.com/12685275/55565793-81a47f00-56c8-11e9-9ba6-528ff0ea12b9.png)

Thank you

**Comment by sasa42** [comment]
you must choose a shorter path for download location and project location because of....

com.unity.template.dxr-1.0.0-preview.tgz
could not be fully extracted and manged because of very long filenames on Windows

e.g
Unity-Experimental-DXR\Data\Resources\PackageManager\ProjectTemplates\com.unity.template.dxr-1.0.0-preview\package\ProjectData~\Assets\3D MODEL\PROPS\Meeting_Room_Cradenza_01\New\Meeting_Room_Cradenza_01_Meeting_Room_Cradenza_01BaseColor.png

count is 241 charakters. windows max is 260 without hacking registry. only 19 left to run .)

**Comment by sasa42** [comment]
you must choose a shorter path for download location and project location because of....

com.unity.template.dxr-1.0.0-preview.tgz
could not be fully extracted and manged because of very long filenames on Windows

e.g
Unity-Experimental-DXR\Data\Resources\PackageManager\ProjectTemplates\com.unity.template.dxr-1.0.0-preview\package\ProjectData~\Assets\3D MODEL\PROPS\Meeting_Room_Cradenza_01\New\Meeting_Room_Cradenza_01_Meeting_Room_Cradenza_01BaseColor.png

count is 241 charakters. windows max is 260 without hacking registry. only 19 left to run .)
C:\Users\caio\downl ****oads is 4 charakters too much.)

**Comment by cjsb** [comment]
Perfect, it is working! Thank you! =)
