### ISSUE TITLE
Unable to expand /Data/Resources/PackageManager/ProjectTemplates/com.unity.template.dxr-1.0.0-preview.tgz

### ISSUE THREAD

**Issue by sirakzg** [Unity-Technologies/Unity-Experimental-DXR#4]
Can't create new project, even with the 1.6 GB file checked out during a clone.

Manually uncompressed the .tgz file to expose the project files.

**Comment by ChristianPayne** [comment]
I can't seem to get this to work. Did you just uncompress the .tgz file and that's it or were there files that you moved around?

**Comment by AgentLee** [comment]
I had some issues too but eventually got it to work (WinRar default extracted it into /ProjectTemplates/com.unity.template.dxr-1.0.0-preview.tgz/). 

Make sure you uncompress the .tgz into /ProjectTemplates directly so it'd be /ProjectTemplates/pacakge rather than /ProjectTemplates/com.unity.template.dxr-1.0.0-preview.tgz/package.

I ended up deleting the .tgz afterwards to get it to open.

**Comment by marshmatter** [comment]
I was having similar issues via manually downloading the project file and the proper Unity.exe. 

Doing a proper _git lfs clone_ of the repo did the trick and everything worked fine with creating project.

**Comment by michael430unity** [comment]
I found out that if your user profile is not in the default C:  or Windows system partition, then u got the decompress error. 
I solved this issue by created a new unity project in C: partition.

**Comment by sasa42** [comment]
shortest path actions because of
com.unity.template.dxr-1.0.0-preview.tgz
could not be fully extracted and manged because of very long filenames on Windows

e.g
Unity-Experimental-DXR\Data\Resources\PackageManager\ProjectTemplates\com.unity.template.dxr-1.0.0-preview\package\ProjectData~\Assets\3D MODEL\PROPS\Meeting_Room_Cradenza_01\New\Meeting_Room_Cradenza_01_Meeting_Room_Cradenza_01BaseColor.png

count is 241 charakters. windows max is 260 without hacking registry. only 19 left to run .)

**Comment by sebastienlagarde** [comment]
Hi, thanks for the report. Added the information to the readme. And move some files in folders to allow more character. Still low (allow around 30-35 character).
