### ISSUE TITLE
Crashes after completing the import of the template.

### ISSUE THREAD

**Issue by jeremedia** [Unity-Technologies/Unity-Experimental-DXR#5]
Takes quite a while to import the template, then crashes. The Crash Reporter appears briefly but it too crashes, or quits. Tried five times so far.

i7-6700K
32GB RAM
2080 Ti
Windows Build 1903, which may be the problem.

**Comment by oscarbg** [comment]
+1
Have the same exact issue.. I thought it was because I was using too many "beta" things:
a) Windows 20H1 insider 18865
b) NV 430.00 WDDM 2.6 Insider driver
or because:
c)I'm using a Titan V (that altough has DXR support lacks Tensor Cores)..
as I see on Unity folder new Gameworks raytracing dlls:
GFSDK_RTAO_D3D12.win64.dll
GFSDK_RTReflections_D3D12.win64.dll
maybe because these libs are supported only on Turing GPUs?

**Comment by jeremedia** [comment]
Project opened after updating to latest build of Windows 1903.

**Comment by jeremedia** [comment]
Not sure if the Windows update was the reason.
