### ISSUE TITLE
Unity.exe not working

### ISSUE THREAD

**Issue by Alterart** [Unity-Technologies/Unity-Experimental-DXR#8]
I cant run Unity.exe.
It says " this application wont work on this computer" 
my spec: 
Windows 10 Pro build 1809
rtx 2070
I just download from github and unpack zip file.

**Comment by hi1213345446231** [comment]
same issue

**Comment by ProOmicron** [comment]
same issue

**Comment by unitycoder** [comment]
you need to clone with git large file system (otherwise that unity.exe is 1kb text file only)
more info,
https://forum.unity.com/threads/unity-experimental-hdrp-dxr.656092/#post-4402879

i used [sourcetree](https://www.sourcetreeapp.com/) for cloning, so it automatically did all the necessary steps..

**Comment by Alterart** [comment]
Thank you very much! I installed sourcetree and cloned this repo. Everything working fine now :)

> 
> 
> you need to clone with git large file system (otherwise that unity.exe is 1kb text file only)
> more info,
> https://forum.unity.com/threads/unity-experimental-hdrp-dxr.656092/#post-4402879
> 
> i used [sourcetree](https://www.sourcetreeapp.com/) for cloning, so it automatically did all the necessary steps..

**Comment by sebastienlagarde** [comment]
Thanks for the information. Added to the instruction.
